// Shared by execution and static compatibility reports.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum StepRunner {
    OpenUrl,
    StateStorage,
    MsgBox,
    SelectFolder,
    UserInput,
    Delay,
    KeyInput,
    GetClipboardText,
    WaitClipboardChange,
    GetSelectedText,
    ActivateProcessMainWindow,
    WriteClipboard,
    RegexExtract,
    StringProcess,
    Download,
    ReadFile,
    Imageinfo,
    ImgToBase64,
    FileOperation,
    SplitString,
    Assign,
    StrReplace,
    SimpleIf,
    If,
    Repeat,
    Each,
    Break,
    Continue,
    Group,
    Stop,
    Subprogram,
    FormatString,
    Notify,
    ReportProgress,
    OutputText,
}

impl StepRunner {
    pub(super) fn from_key(key: &str) -> Option<Self> {
        Some(match key {
            "sys:openUrl" => Self::OpenUrl,
            "sys:stateStorage" => Self::StateStorage,
            "sys:MsgBox" => Self::MsgBox,
            "sys:selectFolder" => Self::SelectFolder,
            "sys:userInput" => Self::UserInput,
            "sys:delay" => Self::Delay,
            "sys:keyInput" => Self::KeyInput,
            "sys:getClipboardText" => Self::GetClipboardText,
            "sys:waitClipboardChange" => Self::WaitClipboardChange,
            "sys:getSelectedText" => Self::GetSelectedText,
            "sys:activateProcessMainWindow" => Self::ActivateProcessMainWindow,
            "sys:writeClipboard" => Self::WriteClipboard,
            "sys:regexExtract" => Self::RegexExtract,
            "sys:stringProcess" => Self::StringProcess,
            "sys:download" => Self::Download,
            "sys:readFile" => Self::ReadFile,
            "sys:imageinfo" => Self::Imageinfo,
            "sys:imgToBase64" => Self::ImgToBase64,
            "sys:fileOperation" => Self::FileOperation,
            "sys:splitString" => Self::SplitString,
            "sys:assign" => Self::Assign,
            "sys:strReplace" => Self::StrReplace,
            "sys:simpleIf" => Self::SimpleIf,
            "sys:if" => Self::If,
            "sys:repeat" => Self::Repeat,
            "sys:each" => Self::Each,
            "sys:break" => Self::Break,
            "sys:continue" => Self::Continue,
            "sys:group" => Self::Group,
            "sys:stop" => Self::Stop,
            "sys:subprogram" => Self::Subprogram,
            "sys:formatString" => Self::FormatString,
            "sys:notify" => Self::Notify,
            "sys:reportProgress" => Self::ReportProgress,
            "sys:outputText" => Self::OutputText,
            _ => return None,
        })
    }
}
